team_map = {'Air Force': {'COLLEGE_FOOTBALL_DATA': 'Air Force', 'SP_PLUS': 'Air Force', 'FPI': 'Air Force',
                          'ENTROPY': 'Air Force', 'MASSEY': 'Air Force'},
            'Akron': {'COLLEGE_FOOTBALL_DATA': 'Akron', 'SP_PLUS': 'Akron', 'FPI': 'Akron', 'ENTROPY': 'Akron',
                      'MASSEY': 'null'},
            'Alabama': {'COLLEGE_FOOTBALL_DATA': 'Alabama', 'SP_PLUS': 'Alabama', 'FPI': 'Alabama',
                        'ENTROPY': 'Alabama', 'MASSEY': 'Alabama'},
            'Appalachian State': {'COLLEGE_FOOTBALL_DATA': 'Appalachian State', 'SP_PLUS': 'Appalachian State',
                                  'FPI': 'Appalachian St', 'ENTROPY': 'Appalachian State', 'MASSEY': 'null'},
            'Arizona': {'COLLEGE_FOOTBALL_DATA': 'Arizona', 'SP_PLUS': 'Arizona', 'FPI': 'Arizona',
                        'ENTROPY': 'Arizona', 'MASSEY': 'Arizona U'},
            'Arizona State': {'COLLEGE_FOOTBALL_DATA': 'Arizona State', 'SP_PLUS': 'Arizona State',
                              'FPI': 'Arizona State', 'ENTROPY': 'Arizona State', 'MASSEY': 'Arizona State'},
            'Arkansas': {'COLLEGE_FOOTBALL_DATA': 'Arkansas', 'SP_PLUS': 'Arkansas', 'FPI': 'Arkansas',
                         'ENTROPY': 'Arkansas', 'MASSEY': 'Arkansas'},
            'Arkansas State': {'COLLEGE_FOOTBALL_DATA': 'Arkansas State', 'SP_PLUS': 'Arkansas State',
                               'FPI': 'Arkansas State', 'ENTROPY': 'Arkansas State', 'MASSEY': 'Arkansas State'},
            'Army': {'COLLEGE_FOOTBALL_DATA': 'Army', 'SP_PLUS': 'Army', 'FPI': 'Army', 'ENTROPY': 'Army',
                     'MASSEY': 'Army'},
            'Auburn': {'COLLEGE_FOOTBALL_DATA': 'Auburn', 'SP_PLUS': 'Auburn', 'FPI': 'Auburn', 'ENTROPY': 'Auburn',
                       'MASSEY': 'Auburn'},
            'Ball State': {'COLLEGE_FOOTBALL_DATA': 'Ball State', 'SP_PLUS': 'Ball State', 'FPI': 'Ball State',
                           'ENTROPY': 'Ball State', 'MASSEY': 'null'},
            'Baylor': {'COLLEGE_FOOTBALL_DATA': 'Baylor', 'SP_PLUS': 'Baylor', 'FPI': 'Baylor', 'ENTROPY': 'Baylor',
                       'MASSEY': 'Baylor'},
            'Boise State': {'COLLEGE_FOOTBALL_DATA': 'Boise State', 'SP_PLUS': 'Boise State', 'FPI': 'Boise State',
                            'ENTROPY': 'Boise State', 'MASSEY': 'Boise State'},
            'Boston College': {'COLLEGE_FOOTBALL_DATA': 'Boston College', 'SP_PLUS': 'Boston College',
                               'FPI': 'Boston College', 'ENTROPY': 'Boston College', 'MASSEY': 'Boston College'},
            'Bowling Green': {'COLLEGE_FOOTBALL_DATA': 'Bowling Green', 'SP_PLUS': 'Bowling Green',
                              'FPI': 'Bowling Green', 'ENTROPY': 'Bowling Green', 'MASSEY': 'null'},
            'Buffalo': {'COLLEGE_FOOTBALL_DATA': 'Buffalo', 'SP_PLUS': 'Buffalo', 'FPI': 'Buffalo',
                        'ENTROPY': 'Buffalo', 'MASSEY': 'null'},
            'BYU': {'COLLEGE_FOOTBALL_DATA': 'BYU', 'SP_PLUS': 'BYU', 'FPI': 'BYU', 'ENTROPY': 'B.Y.U.',
                    'MASSEY': 'BYU'},
            'California': {'COLLEGE_FOOTBALL_DATA': 'California', 'SP_PLUS': 'California', 'FPI': 'Cal',
                           'ENTROPY': 'California', 'MASSEY': 'California'},
            'Central Michigan': {'COLLEGE_FOOTBALL_DATA': 'Central Michigan', 'SP_PLUS': 'Central Michigan',
                                 'FPI': 'Cent Michigan', 'ENTROPY': 'Central Michigan', 'MASSEY': 'null'},
            'Charlotte': {'COLLEGE_FOOTBALL_DATA': 'Charlotte', 'SP_PLUS': 'Charlotte', 'FPI': 'Charlotte',
                          'ENTROPY': 'Charlotte', 'MASSEY': 'null'},
            'Cincinnati': {'COLLEGE_FOOTBALL_DATA': 'Cincinnati', 'SP_PLUS': 'Cincinnati', 'FPI': 'Cincinnati',
                           'ENTROPY': 'Cincinnati', 'MASSEY': 'Cincinnati U'},
            'Clemson': {'COLLEGE_FOOTBALL_DATA': 'Clemson', 'SP_PLUS': 'Clemson', 'FPI': 'Clemson',
                        'ENTROPY': 'Clemson', 'MASSEY': 'Clemson'},
            'Coastal Carolina': {'COLLEGE_FOOTBALL_DATA': 'Coastal Carolina', 'SP_PLUS': 'Coastal Carolina',
                                 'FPI': 'C. Carolina', 'ENTROPY': 'Coastal Carolina', 'MASSEY': 'null'},
            'Colorado': {'COLLEGE_FOOTBALL_DATA': 'Colorado', 'SP_PLUS': 'Colorado', 'FPI': 'Colorado',
                         'ENTROPY': 'Colorado', 'MASSEY': 'Colorado'},
            'Colorado State': {'COLLEGE_FOOTBALL_DATA': 'Colorado State', 'SP_PLUS': 'Colorado State',
                               'FPI': 'Colorado State', 'ENTROPY': 'Colorado State', 'MASSEY': 'Colorado State'},
            'Connecticut': {'COLLEGE_FOOTBALL_DATA': 'Connecticut', 'SP_PLUS': 'Connecticut', 'FPI': 'UConn',
                            'ENTROPY': 'Connecticut', 'MASSEY': 'Connecticut'},
            'Duke': {'COLLEGE_FOOTBALL_DATA': 'Duke', 'SP_PLUS': 'Duke', 'FPI': 'Duke', 'ENTROPY': 'Duke',
                     'MASSEY': 'Duke'},
            'East Carolina': {'COLLEGE_FOOTBALL_DATA': 'East Carolina', 'SP_PLUS': 'East Carolina',
                              'FPI': 'East Carolina', 'ENTROPY': 'East Carolina', 'MASSEY': 'East Carolina'},
            'Eastern Michigan': {'COLLEGE_FOOTBALL_DATA': 'Eastern Michigan', 'SP_PLUS': 'Eastern Michigan',
                                 'FPI': 'E Michigan', 'ENTROPY': 'Eastern Michigan', 'MASSEY': 'null'},
            'Florida': {'COLLEGE_FOOTBALL_DATA': 'Florida', 'SP_PLUS': 'Florida', 'FPI': 'Florida',
                        'ENTROPY': 'Florida', 'MASSEY': 'Florida'},
            'Florida Atlantic': {'COLLEGE_FOOTBALL_DATA': 'Florida Atlantic', 'SP_PLUS': 'Florida Atlantic',
                                 'FPI': 'FAU', 'ENTROPY': 'Florida Atlantic', 'MASSEY': 'null'},
            'Florida International': {'COLLEGE_FOOTBALL_DATA': 'Florida International',
                                      'SP_PLUS': 'Florida International', 'FPI': 'Florida Intl',
                                      'ENTROPY': 'Florida International', 'MASSEY': 'null'},
            'Florida State': {'COLLEGE_FOOTBALL_DATA': 'Florida State', 'SP_PLUS': 'Florida State',
                              'FPI': 'Florida State', 'ENTROPY': 'Florida State', 'MASSEY': 'Florida State'},
            'Fresno State': {'COLLEGE_FOOTBALL_DATA': 'Fresno State', 'SP_PLUS': 'Fresno State', 'FPI': 'Fresno State',
                             'ENTROPY': 'Fresno State', 'MASSEY': 'Fresno State'},
            'Georgia': {'COLLEGE_FOOTBALL_DATA': 'Georgia', 'SP_PLUS': 'Georgia', 'FPI': 'Georgia',
                        'ENTROPY': 'Georgia', 'MASSEY': 'Georgia'},
            'Georgia Southern': {'COLLEGE_FOOTBALL_DATA': 'Georgia Southern', 'SP_PLUS': 'Georgia Southern',
                                 'FPI': 'Ga Southern', 'ENTROPY': 'Georgia Southern', 'MASSEY': 'null'},
            'Georgia State': {'COLLEGE_FOOTBALL_DATA': 'Georgia State', 'SP_PLUS': 'Georgia State',
                              'FPI': 'Georgia State', 'ENTROPY': 'Georgia State', 'MASSEY': 'null'},
            'Georgia Tech': {'COLLEGE_FOOTBALL_DATA': 'Georgia Tech', 'SP_PLUS': 'Georgia Tech', 'FPI': 'Georgia Tech',
                             'ENTROPY': 'Georgia Tech', 'MASSEY': 'Georgia Tech'},
            "Hawai'i": {'COLLEGE_FOOTBALL_DATA': "Hawai'i", 'SP_PLUS': 'Hawaii', 'FPI': "Hawai'i", 'ENTROPY': 'Hawaii',
                        'MASSEY': 'Hawaii'},
            'Houston': {'COLLEGE_FOOTBALL_DATA': 'Houston', 'SP_PLUS': 'Houston', 'FPI': 'Houston',
                        'ENTROPY': 'Houston', 'MASSEY': 'Houston U'},
            'Illinois': {'COLLEGE_FOOTBALL_DATA': 'Illinois', 'SP_PLUS': 'Illinois', 'FPI': 'Illinois',
                         'ENTROPY': 'Illinois', 'MASSEY': 'null'},
            'Indiana': {'COLLEGE_FOOTBALL_DATA': 'Indiana', 'SP_PLUS': 'Indiana', 'FPI': 'Indiana',
                        'ENTROPY': 'Indiana', 'MASSEY': 'Indiana'},
            'Iowa': {'COLLEGE_FOOTBALL_DATA': 'Iowa', 'SP_PLUS': 'Iowa', 'FPI': 'Iowa', 'ENTROPY': 'Iowa',
                     'MASSEY': 'Iowa'},
            'Iowa State': {'COLLEGE_FOOTBALL_DATA': 'Iowa State', 'SP_PLUS': 'Iowa State', 'FPI': 'Iowa State',
                           'ENTROPY': 'Iowa State', 'MASSEY': 'Iowa State'},
            'Kansas': {'COLLEGE_FOOTBALL_DATA': 'Kansas', 'SP_PLUS': 'Kansas', 'FPI': 'Kansas', 'ENTROPY': 'Kansas',
                       'MASSEY': 'Kansas'},
            'Kansas State': {'COLLEGE_FOOTBALL_DATA': 'Kansas State', 'SP_PLUS': 'Kansas State', 'FPI': 'Kansas State',
                             'ENTROPY': 'Kansas State', 'MASSEY': 'Kansas State'},
            'Kent State': {'COLLEGE_FOOTBALL_DATA': 'Kent State', 'SP_PLUS': 'Kent State', 'FPI': 'Kent State',
                           'ENTROPY': 'Kent State', 'MASSEY': 'null'},
            'Kentucky': {'COLLEGE_FOOTBALL_DATA': 'Kentucky', 'SP_PLUS': 'Kentucky', 'FPI': 'Kentucky',
                         'ENTROPY': 'Kentucky', 'MASSEY': 'Kentucky'},
            'Louisiana': {'COLLEGE_FOOTBALL_DATA': 'Louisiana', 'SP_PLUS': 'UL-Lafayette', 'FPI': 'Louisiana',
                          'ENTROPY': 'Louisiana-Lafayette', 'MASSEY': 'null'},
            'Louisiana Monroe': {'COLLEGE_FOOTBALL_DATA': 'Louisiana Monroe', 'SP_PLUS': 'UL-Monroe',
                                 'FPI': 'UL Monroe', 'ENTROPY': 'Louisiana-Monroe', 'MASSEY': 'null'},
            'Louisiana Tech': {'COLLEGE_FOOTBALL_DATA': 'Louisiana Tech', 'SP_PLUS': 'Louisiana Tech', 'FPI': 'LA Tech',
                               'ENTROPY': 'Louisiana Tech', 'MASSEY': 'null'},
            'Louisville': {'COLLEGE_FOOTBALL_DATA': 'Louisville', 'SP_PLUS': 'Louisville', 'FPI': 'Louisville',
                           'ENTROPY': 'Louisville', 'MASSEY': 'Louisville'},
            'LSU': {'COLLEGE_FOOTBALL_DATA': 'LSU', 'SP_PLUS': 'LSU', 'FPI': 'LSU', 'ENTROPY': 'L.S.U.',
                    'MASSEY': 'LSU'},
            'Marshall': {'COLLEGE_FOOTBALL_DATA': 'Marshall', 'SP_PLUS': 'Marshall', 'FPI': 'Marshall',
                         'ENTROPY': 'Marshall', 'MASSEY': 'Marshall'},
            'Maryland': {'COLLEGE_FOOTBALL_DATA': 'Maryland', 'SP_PLUS': 'Maryland', 'FPI': 'Maryland',
                         'ENTROPY': 'Maryland', 'MASSEY': 'Maryland'},
            'Memphis': {'COLLEGE_FOOTBALL_DATA': 'Memphis', 'SP_PLUS': 'Memphis', 'FPI': 'Memphis',
                        'ENTROPY': 'Memphis', 'MASSEY': 'Memphis'},
            'Miami': {'COLLEGE_FOOTBALL_DATA': 'Miami', 'SP_PLUS': 'Miami', 'FPI': 'Miami', 'ENTROPY': 'Miami',
                      'MASSEY': 'Miami Florida'},
            'Miami (OH)': {'COLLEGE_FOOTBALL_DATA': 'Miami (OH)', 'SP_PLUS': 'Miami (Ohio)', 'FPI': 'Miami (OH)',
                           'ENTROPY': 'Miami (Ohio)', 'MASSEY': 'null'},
            'Michigan': {'COLLEGE_FOOTBALL_DATA': 'Michigan', 'SP_PLUS': 'Michigan', 'FPI': 'Michigan',
                         'ENTROPY': 'Michigan', 'MASSEY': 'Michigan'},
            'Michigan State': {'COLLEGE_FOOTBALL_DATA': 'Michigan State', 'SP_PLUS': 'Michigan State',
                               'FPI': 'Mich. St.', 'ENTROPY': 'Michigan State', 'MASSEY': 'Michigan State'},
            'Middle Tennessee': {'COLLEGE_FOOTBALL_DATA': 'Middle Tennessee', 'SP_PLUS': 'Middle Tennessee',
                                 'FPI': 'Mid Tennessee', 'ENTROPY': 'Middle Tennessee State', 'MASSEY': 'null'},
            'Minnesota': {'COLLEGE_FOOTBALL_DATA': 'Minnesota', 'SP_PLUS': 'Minnesota', 'FPI': 'Minnesota',
                          'ENTROPY': 'Minnesota', 'MASSEY': 'Minnesota U'},
            'Mississippi State': {'COLLEGE_FOOTBALL_DATA': 'Mississippi State', 'SP_PLUS': 'Mississippi State',
                                  'FPI': 'Miss St', 'ENTROPY': 'Mississippi State', 'MASSEY': 'Mississippi State'},
            'Missouri': {'COLLEGE_FOOTBALL_DATA': 'Missouri', 'SP_PLUS': 'Missouri', 'FPI': 'Missouri',
                         'ENTROPY': 'Missouri', 'MASSEY': 'Missouri'},
            'Navy': {'COLLEGE_FOOTBALL_DATA': 'Navy', 'SP_PLUS': 'Navy', 'FPI': 'Navy', 'ENTROPY': 'Navy',
                     'MASSEY': 'Navy'},
            'NC State': {'COLLEGE_FOOTBALL_DATA': 'NC State', 'SP_PLUS': 'NC State', 'FPI': 'NC State',
                         'ENTROPY': 'North Carolina State', 'MASSEY': 'NC State'},
            'Nebraska': {'COLLEGE_FOOTBALL_DATA': 'Nebraska', 'SP_PLUS': 'Nebraska', 'FPI': 'Nebraska',
                         'ENTROPY': 'Nebraska', 'MASSEY': 'Nebraska'},
            'Nevada': {'COLLEGE_FOOTBALL_DATA': 'Nevada', 'SP_PLUS': 'Nevada', 'FPI': 'Nevada', 'ENTROPY': 'Nevada',
                       'MASSEY': 'Nevada'},
            'New Mexico': {'COLLEGE_FOOTBALL_DATA': 'New Mexico', 'SP_PLUS': 'New Mexico', 'FPI': 'New Mexico',
                           'ENTROPY': 'New Mexico', 'MASSEY': 'null'},
            'North Carolina': {'COLLEGE_FOOTBALL_DATA': 'North Carolina', 'SP_PLUS': 'North Carolina',
                               'FPI': 'North Carolina', 'ENTROPY': 'North Carolina', 'MASSEY': 'North Carolina'},
            'Northern Illinois': {'COLLEGE_FOOTBALL_DATA': 'Northern Illinois', 'SP_PLUS': 'Northern Illinois',
                                  'FPI': 'N Illinois', 'ENTROPY': 'Northern Illinois', 'MASSEY': 'null'},
            'North Texas': {'COLLEGE_FOOTBALL_DATA': 'North Texas', 'SP_PLUS': 'North Texas', 'FPI': 'North Texas',
                            'ENTROPY': 'North Texas', 'MASSEY': 'null'},
            'Northwestern': {'COLLEGE_FOOTBALL_DATA': 'Northwestern', 'SP_PLUS': 'Northwestern', 'FPI': 'Northwestern',
                             'ENTROPY': 'Northwestern', 'MASSEY': 'Northwestern'},
            'Notre Dame': {'COLLEGE_FOOTBALL_DATA': 'Notre Dame', 'SP_PLUS': 'Notre Dame', 'FPI': 'Notre Dame',
                           'ENTROPY': 'Notre Dame', 'MASSEY': 'Notre Dame'},
            'Ohio': {'COLLEGE_FOOTBALL_DATA': 'Ohio', 'SP_PLUS': 'Ohio', 'FPI': 'Ohio', 'ENTROPY': 'Ohio',
                     'MASSEY': 'null'},
            'Ohio State': {'COLLEGE_FOOTBALL_DATA': 'Ohio State', 'SP_PLUS': 'Ohio State', 'FPI': 'Ohio State',
                           'ENTROPY': 'Ohio State', 'MASSEY': 'Ohio State'},
            'Oklahoma': {'COLLEGE_FOOTBALL_DATA': 'Oklahoma', 'SP_PLUS': 'Oklahoma', 'FPI': 'Oklahoma',
                         'ENTROPY': 'Oklahoma', 'MASSEY': 'Oklahoma'},
            'Oklahoma State': {'COLLEGE_FOOTBALL_DATA': 'Oklahoma State', 'SP_PLUS': 'Oklahoma State',
                               'FPI': 'Oklahoma State', 'ENTROPY': 'Oklahoma State', 'MASSEY': 'Oklahoma State'},
            'Old Dominion': {'COLLEGE_FOOTBALL_DATA': 'Old Dominion', 'SP_PLUS': 'Old Dominion', 'FPI': 'Old Dominion',
                             'ENTROPY': 'Old Dominion', 'MASSEY': 'null'},
            'Ole Miss': {'COLLEGE_FOOTBALL_DATA': 'Ole Miss', 'SP_PLUS': 'Ole Miss', 'FPI': 'Ole Miss',
                         'ENTROPY': 'Ole Miss', 'MASSEY': 'null'},
            'Oregon': {'COLLEGE_FOOTBALL_DATA': 'Oregon', 'SP_PLUS': 'Oregon', 'FPI': 'Oregon', 'ENTROPY': 'Oregon',
                       'MASSEY': 'Oregon'},
            'Oregon State': {'COLLEGE_FOOTBALL_DATA': 'Oregon State', 'SP_PLUS': 'Oregon State', 'FPI': 'Oregon St',
                             'ENTROPY': 'Oregon State', 'MASSEY': 'Oregon State'},
            'Penn State': {'COLLEGE_FOOTBALL_DATA': 'Penn State', 'SP_PLUS': 'Penn State', 'FPI': 'Penn State',
                           'ENTROPY': 'Penn State', 'MASSEY': 'Penn State'},
            'Pittsburgh': {'COLLEGE_FOOTBALL_DATA': 'Pittsburgh', 'SP_PLUS': 'Pittsburgh', 'FPI': 'Pitt',
                           'ENTROPY': 'Pittsburgh', 'MASSEY': 'Pittsburgh U'},
            'Purdue': {'COLLEGE_FOOTBALL_DATA': 'Purdue', 'SP_PLUS': 'Purdue', 'FPI': 'Purdue', 'ENTROPY': 'Purdue',
                       'MASSEY': 'Purdue'},
            'Rice': {'COLLEGE_FOOTBALL_DATA': 'Rice', 'SP_PLUS': 'Rice', 'FPI': 'Rice', 'ENTROPY': 'Rice',
                     'MASSEY': 'null'},
            'Rutgers': {'COLLEGE_FOOTBALL_DATA': 'Rutgers', 'SP_PLUS': 'Rutgers', 'FPI': 'Rutgers',
                        'ENTROPY': 'Rutgers', 'MASSEY': 'null'},
            'San Diego State': {'COLLEGE_FOOTBALL_DATA': 'San Diego State', 'SP_PLUS': 'San Diego State',
                                'FPI': 'San Diego State', 'ENTROPY': 'San Diego State', 'MASSEY': 'San Diego State'},
            'San JosÈ State': {'COLLEGE_FOOTBALL_DATA': 'San JosÈ State', 'SP_PLUS': 'San Jose State',
                               'FPI': 'San Jose State', 'ENTROPY': 'San Jose State', 'MASSEY': 'San Jose State'},
            'SMU': {'COLLEGE_FOOTBALL_DATA': 'SMU', 'SP_PLUS': 'SMU', 'FPI': 'SMU', 'ENTROPY': 'S.M.U.',
                    'MASSEY': 'SMU'},
            'South Alabama': {'COLLEGE_FOOTBALL_DATA': 'South Alabama', 'SP_PLUS': 'South Alabama',
                              'FPI': 'South Alabama', 'ENTROPY': 'South Alabama', 'MASSEY': 'South Alabama'},
            'South Carolina': {'COLLEGE_FOOTBALL_DATA': 'South Carolina', 'SP_PLUS': 'South Carolina',
                               'FPI': 'S Carolina', 'ENTROPY': 'South Carolina', 'MASSEY': 'South Carolina'},
            'Southern Mississippi': {'COLLEGE_FOOTBALL_DATA': 'Southern Mississippi', 'SP_PLUS': 'Southern Miss',
                                     'FPI': 'Southern Miss', 'ENTROPY': 'Southern Miss', 'MASSEY': 'null'},
            'South Florida': {'COLLEGE_FOOTBALL_DATA': 'South Florida', 'SP_PLUS': 'USF', 'FPI': 'USF',
                              'ENTROPY': 'South Florida', 'MASSEY': 'South Florida'},
            'Stanford': {'COLLEGE_FOOTBALL_DATA': 'Stanford', 'SP_PLUS': 'Stanford', 'FPI': 'Stanford',
                         'ENTROPY': 'Stanford', 'MASSEY': 'Stanford'},
            'Syracuse': {'COLLEGE_FOOTBALL_DATA': 'Syracuse', 'SP_PLUS': 'Syracuse', 'FPI': 'Syracuse',
                         'ENTROPY': 'Syracuse', 'MASSEY': 'Syracuse'},
            'TCU': {'COLLEGE_FOOTBALL_DATA': 'TCU', 'SP_PLUS': 'TCU', 'FPI': 'TCU', 'ENTROPY': 'T.C.U.',
                    'MASSEY': 'TCU'},
            'Temple': {'COLLEGE_FOOTBALL_DATA': 'Temple', 'SP_PLUS': 'Temple', 'FPI': 'Temple', 'ENTROPY': 'Temple',
                       'MASSEY': 'Temple'},
            'Tennessee': {'COLLEGE_FOOTBALL_DATA': 'Tennessee', 'SP_PLUS': 'Tennessee', 'FPI': 'Tennessee',
                          'ENTROPY': 'Tennessee', 'MASSEY': 'Tennessee U'},
            'Texas': {'COLLEGE_FOOTBALL_DATA': 'Texas', 'SP_PLUS': 'Texas', 'FPI': 'Texas', 'ENTROPY': 'Texas',
                      'MASSEY': 'Texas'},
            'Texas A&M': {'COLLEGE_FOOTBALL_DATA': 'Texas A&M', 'SP_PLUS': 'Texas A&M', 'FPI': 'Texas A&M',
                          'ENTROPY': 'Texas A&M', 'MASSEY': 'Texas A&M'},
            'Texas State': {'COLLEGE_FOOTBALL_DATA': 'Texas State', 'SP_PLUS': 'Texas State', 'FPI': 'Texas State',
                            'ENTROPY': 'Texas State', 'MASSEY': 'null'},
            'Texas Tech': {'COLLEGE_FOOTBALL_DATA': 'Texas Tech', 'SP_PLUS': 'Texas Tech', 'FPI': 'Texas Tech',
                           'ENTROPY': 'Texas Tech', 'MASSEY': 'Texas Tech'},
            'Toledo': {'COLLEGE_FOOTBALL_DATA': 'Toledo', 'SP_PLUS': 'Toledo', 'FPI': 'Toledo', 'ENTROPY': 'Toledo',
                       'MASSEY': 'null'},
            'Troy': {'COLLEGE_FOOTBALL_DATA': 'Troy', 'SP_PLUS': 'Troy', 'FPI': 'Troy', 'ENTROPY': 'Troy',
                     'MASSEY': 'Troy'},
            'Tulane': {'COLLEGE_FOOTBALL_DATA': 'Tulane', 'SP_PLUS': 'Tulane', 'FPI': 'Tulane', 'ENTROPY': 'Tulane',
                       'MASSEY': 'Tulane'},
            'Tulsa': {'COLLEGE_FOOTBALL_DATA': 'Tulsa', 'SP_PLUS': 'Tulsa', 'FPI': 'Tulsa', 'ENTROPY': 'Tulsa',
                      'MASSEY': 'Tulsa'},
            'UAB': {'COLLEGE_FOOTBALL_DATA': 'UAB', 'SP_PLUS': 'UAB', 'FPI': 'UAB', 'ENTROPY': 'U.A.B.',
                    'MASSEY': 'null'},
            'UCF': {'COLLEGE_FOOTBALL_DATA': 'UCF', 'SP_PLUS': 'UCF', 'FPI': 'UCF', 'ENTROPY': 'Central Florida',
                    'MASSEY': 'null'},
            'UCLA': {'COLLEGE_FOOTBALL_DATA': 'UCLA', 'SP_PLUS': 'UCLA', 'FPI': 'UCLA', 'ENTROPY': 'UCLA',
                     'MASSEY': 'UCLA'},
            'UMass': {'COLLEGE_FOOTBALL_DATA': 'UMass', 'SP_PLUS': 'Massachusetts', 'FPI': 'UMass',
                      'ENTROPY': 'Massachusetts', 'MASSEY': 'null'},
            'UNLV': {'COLLEGE_FOOTBALL_DATA': 'UNLV', 'SP_PLUS': 'UNLV', 'FPI': 'UNLV', 'ENTROPY': 'UNLV',
                     'MASSEY': 'UNLV'},
            'USC': {'COLLEGE_FOOTBALL_DATA': 'USC', 'SP_PLUS': 'USC', 'FPI': 'USC', 'ENTROPY': 'Southern Cal',
                    'MASSEY': 'USC'},
            'Utah': {'COLLEGE_FOOTBALL_DATA': 'Utah', 'SP_PLUS': 'Utah', 'FPI': 'Utah', 'ENTROPY': 'Utah',
                     'MASSEY': 'Utah'},
            'Utah State': {'COLLEGE_FOOTBALL_DATA': 'Utah State', 'SP_PLUS': 'Utah State', 'FPI': 'Utah State',
                           'ENTROPY': 'Utah State', 'MASSEY': 'Utah State'},
            'UTEP': {'COLLEGE_FOOTBALL_DATA': 'UTEP', 'SP_PLUS': 'UTEP', 'FPI': 'UTEP', 'ENTROPY': 'UTEP',
                     'MASSEY': 'null'},
            'UT San Antonio': {'COLLEGE_FOOTBALL_DATA': 'UT San Antonio', 'SP_PLUS': 'UTSA', 'FPI': 'UTSA',
                               'ENTROPY': 'UTSA', 'MASSEY': 'null'},
            'Vanderbilt': {'COLLEGE_FOOTBALL_DATA': 'Vanderbilt', 'SP_PLUS': 'Vanderbilt', 'FPI': 'Vanderbilt',
                           'ENTROPY': 'Vanderbilt', 'MASSEY': 'Vanderbilt'},
            'Virginia': {'COLLEGE_FOOTBALL_DATA': 'Virginia', 'SP_PLUS': 'Virginia', 'FPI': 'Virginia',
                         'ENTROPY': 'Virginia', 'MASSEY': 'Virginia'},
            'Virginia Tech': {'COLLEGE_FOOTBALL_DATA': 'Virginia Tech', 'SP_PLUS': 'Virginia Tech',
                              'FPI': 'Virginia Tech', 'ENTROPY': 'Virginia Tech', 'MASSEY': 'Virginia Tech'},
            'Wake Forest': {'COLLEGE_FOOTBALL_DATA': 'Wake Forest', 'SP_PLUS': 'Wake Forest', 'FPI': 'Wake Forest',
                            'ENTROPY': 'Wake Forest', 'MASSEY': 'Wake Forest'},
            'Washington': {'COLLEGE_FOOTBALL_DATA': 'Washington', 'SP_PLUS': 'Washington', 'FPI': 'Washington',
                           'ENTROPY': 'Washington', 'MASSEY': 'Washington U'},
            'Washington State': {'COLLEGE_FOOTBALL_DATA': 'Washington State', 'SP_PLUS': 'Washington State',
                                 'FPI': 'Washington St', 'ENTROPY': 'Washington State', 'MASSEY': 'Washington State'},
            'Western Kentucky': {'COLLEGE_FOOTBALL_DATA': 'Western Kentucky', 'SP_PLUS': 'Western Kentucky',
                                 'FPI': 'W Kentucky', 'ENTROPY': 'Western Kentucky', 'MASSEY': 'null'},
            'Western Michigan': {'COLLEGE_FOOTBALL_DATA': 'Western Michigan', 'SP_PLUS': 'Western Michigan',
                                 'FPI': 'W Michigan', 'ENTROPY': 'Western Michigan', 'MASSEY': 'null'},
            'West Virginia': {'COLLEGE_FOOTBALL_DATA': 'West Virginia', 'SP_PLUS': 'West Virginia',
                              'FPI': 'West Virginia', 'ENTROPY': 'West Virginia', 'MASSEY': 'West Virginia'},
            'Wisconsin': {'COLLEGE_FOOTBALL_DATA': 'Wisconsin', 'SP_PLUS': 'Wisconsin', 'FPI': 'Wisconsin',
                          'ENTROPY': 'Wisconsin', 'MASSEY': 'Wisconsin'},
            'Wyoming': {'COLLEGE_FOOTBALL_DATA': 'Wyoming', 'SP_PLUS': 'Wyoming', 'FPI': 'Wyoming',
                        'ENTROPY': 'Wyoming', 'MASSEY': 'Wyoming'},
            'New Mexico State': {'COLLEGE_FOOTBALL_DATA': 'New Mexico State', 'SP_PLUS': 'New Mexico State',
                                 'FPI': 'New Mexico St', 'ENTROPY': 'New Mexico State', 'MASSEY': 'null'},
            'Liberty': {'COLLEGE_FOOTBALL_DATA': 'Liberty', 'SP_PLUS': 'Liberty', 'FPI': 'Liberty',
                        'ENTROPY': 'Liberty', 'MASSEY': 'null'}}
